FROM node:18.17.1-alpine AS build
WORKDIR /app
COPY package*.json ./ 
RUN npm install
RUN npx ngcc --properties es2023 browser module main --first-only --create-ivy-entry-points                                                                                                --first-only --create-ivy-entry-points
COPY . .
RUN npm run build

#FROM nginx:stable
#COPY nginx.conf /etc/nginx/nginx.conf
##COPY nginx.conf /etc/nginx/conf.d/default.conf
#COPY --from=build /app/dist/barra-app/ /usr/share/nginx/html
#EXPOSE 443
#EXPOSE 80


#FROM ubuntu:18.04
#RUN apt update -y \
#    && apt install nginx curl vim -y \
#    && apt-get install software-properties-common -y \
#    && add-apt-repository ppa:certbot/certbot -y \
#    && apt-get update -y \
#    && apt-get install python-certbot-nginx -y \ 
#    && apt-get clean
#
#COPY nginx.conf /etc/nginx/nginx.conf
#COPY --from=build /app/dist/barra-app/ /usr/share/nginx/html
#EXPOSE 443
#
#EXPOSE 80
#CMD ["nginx","-g","daemon off;"]



FROM nginx:stable AS stage2
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/barra-app/ /usr/share/nginx/html
EXPOSE 443
EXPOSE 80

FROM ubuntu:18.04

RUN apt-get update -y \
    && apt-get install -y curl vim software-properties-common \
    && add-apt-repository ppa:certbot/certbot -y \
    && apt-get update -y \
    && apt-get install -y python-certbot-nginx \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=stage2 /etc/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=stage2 /usr/share/nginx/html/ /usr/share/nginx/html/

EXPOSE 443
EXPOSE 80

CMD ["nginx","-g","daemon off;"]
